-- M2: common CrossFit movements (measure = default measure; items can prescribe any field).
insert into public.exercises (name, measure) values
  ('Back Squat', 'load'),
  ('Front Squat', 'load'),
  ('Overhead Squat', 'load'),
  ('Deadlift', 'load'),
  ('Sumo Deadlift High Pull', 'load'),
  ('Power Clean', 'load'),
  ('Squat Clean', 'load'),
  ('Hang Power Clean', 'load'),
  ('Hang Squat Clean', 'load'),
  ('Clean & Jerk', 'load'),
  ('Power Snatch', 'load'),
  ('Squat Snatch', 'load'),
  ('Hang Power Snatch', 'load'),
  ('Strict Press', 'load'),
  ('Push Press', 'load'),
  ('Push Jerk', 'load'),
  ('Split Jerk', 'load'),
  ('Thruster', 'load'),
  ('Bench Press', 'load'),
  ('Front Rack Lunge', 'load'),
  ('Dumbbell Snatch', 'load'),
  ('Dumbbell Thruster', 'load'),
  ('Devil Press', 'load'),
  ('Goblet Squat', 'load'),
  ('Kettlebell Swing', 'load'),
  ('Wall Ball', 'reps'),
  ('Pull-up', 'reps'),
  ('Chest-to-Bar Pull-up', 'reps'),
  ('Jumping Pull-up', 'reps'),
  ('Ring Row', 'reps'),
  ('Toes-to-Bar', 'reps'),
  ('Knees-to-Elbows', 'reps'),
  ('Bar Muscle-up', 'reps'),
  ('Ring Muscle-up', 'reps'),
  ('Ring Dip', 'reps'),
  ('Handstand Push-up', 'reps'),
  ('Push-up', 'reps'),
  ('Burpee', 'reps'),
  ('Burpee Over the Bar', 'reps'),
  ('Box Jump', 'reps'),
  ('Box Jump Over', 'reps'),
  ('Step-up', 'reps'),
  ('Air Squat', 'reps'),
  ('Pistol', 'reps'),
  ('Lunge', 'reps'),
  ('Sit-up', 'reps'),
  ('GHD Sit-up', 'reps'),
  ('V-up', 'reps'),
  ('Double-Under', 'reps'),
  ('Single-Under', 'reps'),
  ('Rope Climb', 'reps'),
  ('Row', 'calories'),
  ('Assault Bike', 'calories'),
  ('Echo Bike', 'calories'),
  ('Ski Erg', 'calories'),
  ('Run', 'distance'),
  ('Shuttle Run', 'distance'),
  ('Handstand Walk', 'distance'),
  ('Farmer Carry', 'distance'),
  ('Sled Push', 'distance'),
  ('Walking Lunge', 'distance'),
  ('Plank', 'time'),
  ('Hollow Hold', 'time'),
  ('L-Sit', 'time'),
  ('Wall Sit', 'time')
on conflict do nothing;
